#!/bin/bash

echo "# Mozilla User Preferences"
echo ""
echo "/* Do not edit this file."
echo " *"
echo " * If you make changes to this file while the application is running,"
echo " * the changes will be overwritten when the application exits."
echo " *"
echo " * To make a manual change to preferences, you can visit the URL about:config"
echo " */"

cat prefs.orig.js prefs.vilanoo.js | grep -v "^//" | grep -v "^#" | grep -v "^.\*" | sort | uniq